### ISSUE TITLE
Change internal framework request variables paradigm

### ISSUE THREAD

**Issue by aisola** [MasoniteFramework/core#120]
Currently in the framework, we have certain request variables which are usually handled automatically and pose no real value to the end-developer in the controllers. Specifically, I'm talking about `csrf_token` and `request_method`.

I was thinking for the 2.0 release, that they should be changed to `__token` and `__method` respectively.

The big benefit to this is mostly with developers and package maintainers. One use case that I came across was when I was developing a package and I wanted to use Request.all() to get all variables that were pertinent to a form. Right now I just have to filter out the two above, but what happens if I import a third-party package or Masonite adds more convenience request variables? It'll make it a lot more tedious to filter them out. If all of these internal variables all began with a common string (i.e. `__`), then it would be trivial to filter them out.

```python
for field, value in Request.all().items():
    if not field.startswith('__'):
        # ...
```

Does this sound like something we should move forward with for the 2.0 release?

**Comment by josephmancuso** [comment]
sure, the request method actually has no private attributes at all because it was the first class I made and I didn't directly see the benefits of them. If all changes are internal then sure. Since it's mainly internal changes we can base merge this into develop. It might be time to check the internals and make sure everything is good moving forward like this.

**Comment by mapeveri** [comment]
I like the idea.
