### ISSUE TITLE
test "building up drivers" support

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#140]
Not sure what is a better way of explaining this but i'm wondering if there is a way we can do something like:

    $ pip install masonite-deploy

then inside the config:

```python
PROVIDERS = [
    ...

    'deploy.providers.DeployProvider',
]
```

which will have let's say a Heroku deployment driver.

Now if we want other drivers, I think it will be really annoying to now have to do:

    $ pip install masonite-deploy-aws

then inside the config:

```python
PROVIDERS = [
    ...

    'deploy.providers.DeployProvider',
    'deployaws.providers.DeployProvider'
]
```

this seems dumb. I'm wondering if there is a pattern we can follow that allows us to do something like:

    $ pip install masonite-deploy-aws

and then somehow dynamically load that driver into the service provider already there. I have to experiment today with some design patterns that will allow this.

@mapeveri @aisola thoughts?

**Comment by aisola** [comment]
I'm really not sure if this is a good idea. I think it is best to leave deployment mostly up to the end developer. Honestly, deployment requirements differ pretty drastically for each project. I feel like a "Heroku Deployment Guide" and "Digital Ocean Deployment Guide" etc. would be more helpful. That way we don't need to maintain code to deploy to _all the systems_.

If you want to support heroku directly, perhaps we build a custom [Buildpack](https://devcenter.heroku.com/articles/buildpacks). We could legitimately fork the [Python one](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-python) and change it slightly for Masonite.

Ultimately, I'm not really sure that people are going to use this _that much_ in order to make it worth the maintenance cost. I think this is one of the things that is worth exploring solutions outside of the framework itself.

**Comment by josephmancuso** [comment]
Oh no not the actual package idea. That was just a random example. Masonite came with a deploy command that deployed to heroku and was just a wrapper around the cli command and people went nuts on reddit. I'm taking more about the design pattern that will allow us to auto detect drivers as they are installed. That part. 

for example if we want to add drivers is there anyway we can auto detect them without adding a service provider for each and every driver we install to load them into the container? Can we have a service provider that can auto detect the driver we just installed? We would need to have package developers install it something specific I think. This may get too magical though actually and new people coming in might not know where some drivers are loading in from

**Comment by aisola** [comment]
Oh I see. My mistake. That may actually work. The manager pattern should be pretty easy to implement here. It's just a matter of defining the contract.

**Comment by josephmancuso** [comment]
I think what this is trying to do might be too magical in the beginning of the framework. It seems to be better off to explicitly declare somewhere outside of your dependency file where the actual drivers are coming from. I'll close this and possibly reopen for 2.1
