### ISSUE TITLE
View Routes

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#294]
It would be useful to provide this functionality 🤔 :

https://laravel.com/docs/5.6/routing#view-routes

**Comment by josephmancuso** [comment]
Maybe something like:

```
Get().view('/url', {'data', 'here'})
```

This will need to go into the develop release because it will require a more modular change to the route provider to promote better modularization of adding things like these. The code is too explciit in the route provider, we need to make more methods on the route classes so we can modify how behavior works on each route. 

I'll take this issue though since it needs a bit of refactoring first
