### ISSUE TITLE
Improvements list

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#30]
@mapeveri 

# It forces me to install mysql

I like the idea of having all the dependencies you need out of the box. I'm building the framework around what I would wan't a Python framework to be personally which comes with good and bad. The most obvious bad is that it is very opinionated although I've been programming for almost 10 years I definitely have an idea of what I was a framework to be and think I also have an idea what other developers want a framework to be, even if they don't know they want it yet. I personally feel that once we show them the way then they will like it a lot more.

At this point in the framework I want to break away from what other frameworks do and take our own path that we feel is right.

Now with that being said I completely agree that you shouldn't have to install an `apt-get` package on a computer and honestly I didn't know that Linux was such a widely used development platform. If I had to guess I would have thought it was around 50% Mac, 40% windows and 10% Linux but it's more like 20% Linux which is pretty big. 

#### Solution

I think there are 2 solutions here. 1 is to use a different mysql driver (currently its `mysqlclient`) which is the requirement in requirements.txt but there is another one we can install. I'll do some Linux testing soon.

option 2 would be to throw an exception when they first use the model which tells them to install one of the requirements. 

# Install many dependencies, I would have to ask some questions and based on that install.

This is going to have to stay for several reasons. Reason 1 is that the requirements are needed for many of the Service Providers. With a batteries included framework comes many dependencies. This was always a really weird complaint from developers I never understood. Why does it matter that an application has a lot of dependencies? You don't have to use all of them and they are just dependencies. If an application is large in file size that really shouldn't matter these days since nearly all applications will be ran on dedicated servers or cloud infrastructure which has very high amounts of storage. 

Reason 2 is that Service Providers (and drivers) require these dependencies and therefore the install process would ask questions and have to build a `PROVIDERS` list automatically somehow and associate the dependencies with them. I feel like this would be a pretty incredible feat and hard to maintain.

Reason 3 is I hate question installs because when first creating a program, I don't know what I need and I don't want to have to run through an hour of documentation and time to install something I said no to and didn't think I needed. I just want things to be there when I need it.

Also because service providers are designed to load before the server starts, Adding service providers will not slow the application down. Only a very few service providers that are required by the application need to be loaded on every request. if people want to strip the application when it comes time to deploy then they can simply remove service providers before deploying.

* The application generated by craft does not contain PEP8.

I want to keep it this way. To be fair I accepted the PEP8 because it was not client facing and only developers contributing will see it but PEP8 is extremely ugly. like really ugly. I know Python required PEP8 but quite frankly, everyone takes PEP like it's the law of the land and not following by it is death.

Developers have to understand that PEP's are just guidelines and aren't strict measurements. I like the comments and the standards of the application generated by craft because they look beautiful. 

Also know that PEP8 also says:

> Many projects have their own coding style guidelines. In the event of any conflicts, such project-specific guides take precedence for that project.

PEP8 is good for the core library but anything client facing should look nice over PEP8 standards

# Support to sqlite3. I would have to support at least mysql, postgresql and sqlite3.

Orator does support all three. I need to create documentation for Orator from scratch. Their documentation is not the best. I just keep dread writing it because the library has so many features.

# The migrations would be good that you can pass a flag to tell you what type of migration I want and the generator to put a code related to that flag. Why I wanted to create a new table and by default
put me with self.schema.table ('blogs') as table: and when running the migration I made an alter table.

Can you explain this one more? There are only 2 types of migrations needed:

* a creation migration to create tables
* a table migration to do everything else with tables (update, delete, rename, drop etc etc)

if you want to alter a table you simply make the table migration and use the `.change()` method. Again I'll have to create solid documentation on the Orator ORM

# Generate a controller based on a model and that I put together the methods for a crud.

This could be good. Let's open an issue and discuss more about this.

this could be a `craft controller NameOfController --crud` which can fill in the `show` `store` `update` `delete` methods. 

let's talk more about this in an issue

# When you generate a controller, that does not need to put "NameController" with making craft controlller Name, it would have to reach. This is because I generated a "Name" file alone.

Can you explain this more? You want to do something like `craft controller Name` which will append "Controller" to the end?

This might not be good because not all controllers require the "XController" signature. I don't want to force developers to have to call all controllers "XController" (although that is the default convention of Masonite) This can change though if you have other thoughts.

# When a controller is generated, I have the possibility to add the templates.

Do you mean something like `craft controller DashboardController --templates dashboard dashboard/user dashboard/profile`? If so let's open up and issue for this and discuss more. This could be a good feature after some discussion.

# Resource routes.

I like. let's open an issue and discuss how this will work.

# It generates the file of a model with capital letter.

What do you mean? all classes in Masonite are "StuddlyCase" by default so models should keep the class naming convention of Masonite. This is more of a naming convention thing. 

You should be able to do `craft model user` which will create the file name and model name it in lowercase. If this does not then let's open a bug issue

# Generate a model based on a table in the database. So that by default you know which table to use.

Can you explore more? If you name a model the singular and the table the plural then it will default to that table. 

For example, if I have a photos table then I make a model called `Photo` which will automatically point to the `photos` table. If you want to change the table it points to you can specify the `__table__='another_table'` attribute on the model. Again I need to update the documentation.

# Command to create a default user.

Explain this further. You mean like Django's super user? I do agree with this and have realized that I need to do `craft auth` and then sign up manually. Let's open an issue and discuss this

**Comment by mapeveri** [comment]
- The points "It forces me to install mysql" and "Install many dependencies, I would have to ask some questions and based on that install." I think they go together.

Those drivers that need the core, I think it's good that's in the core, now: are all the drivers needed for all the projects? As craft is an excellent tool, 
it would not be good to ask us what drivers we want and then, if later in the project we require a driver that we did not install at the beginning, 
it is installed manually and we will add in the documentation required by the dependence.

What you say is like rails, which comes with everything, but people no longer want to use rails so much in these times, because nobody wants everything to be complete. 
More in the era of microservices.

- The application generated by craft does not contain PEP8.

I like to respect the standars, I think they are there for something.

- Support to sqlite3. I would have to support at least mysql, postgresql and sqlite3.

Great!

- The migrations would be good that you can pass a flag to tell you what type of migration I want and the generator to put a code related to that flag. Why I wanted to create a new table and by default.

Sure, I made my first migration and when I execute it I was doing an alter table, I do not know why these did not detect that it was for a create.

- Generate a controller based on a model and that I put together the methods for a crud.

Exactly :)

- When you generate a controller, that does not need to put "NameController" with making craft controlller Name, it would have to reach. This is because I generated a "Name" file alone.

Ok, but then it would be good to create a convention, so that there are no problems with the names.

- When a controller is generated, I have the possibility to add the templates.

Of course, what I mean is that if I create a controller and this controller has a show method, at least I create the template for that method.

- It generates the file of a model with capital letter.

I like that the names of the files are in miniscule.

- Generate a model based on a table in the database. So that by default you know which table to use.

Ahh I did not know, because I had problems with a model "Article", I was looking for a table "articles".

- Command to create a default user.

Yes like django :)

One last note, in python is more common development under unix operating systems. Like OSX or Linux.

**Comment by josephmancuso** [comment]
# Improvements to focus on:

> it would not be good to ask us what drivers we want and then, if later in the project we require a driver that we did not install at the beginning

I like this idea and any driver that requires a dependency should be installed separately when needed and should throw a `DriverLibraryNotFound` exception which some already do. Look at the broadcast drivers

> Sure, I made my first migration and when I execute it I was doing an alter table, I do not know why these did not detect that it was for a create.

Explain this again further. What were you doing. did you run `craft migration name_of_migration --table table_name` or `craft migration name_of_migration --create table_name`? Notice the difference between `--create` and `--table`

> Generate a controller based on a model and that I put together the methods for a crud.

Yup let's go for it. Let's discuss how this should look and work in it's own issue

> When you generate a controller, that does not need to put "NameController" with making craft controlller Name, it would have to reach. This is because I generated a "Name" file alone.

> Ok, but then it would be good to create a convention, so that there are no problems with the names.

Ok let's go with this. I can't find a good reason to say no so let's do it.

> Of course, what I mean is that if I create a controller and this controller has a show method, at least I create the template for that method.

Can you give a hard example of this? How would the flow of it work?

> Command to create a default user.

Yeah so let's do this to. It will pull in from the `config/auth.py` file. I'm thinking the command should be:

```
craft auth-user --field1 value --field2 value
```

Something like that? It can't be user because many application might change the authentication model to a Company or something.

**Comment by mapeveri** [comment]
- I like this idea and any driver that requires a dependency should be installed separately when needed and should throw a DriverLibraryNotFound exception which some already do. Look at the broadcast drivers

Excellent. I think this is great, because we have to take into account users who just want to do an api-rest or a microservice.

- Explain this again further. What were you doing. did you run craft migration name_of_migration --table table_name or craft migration name_of_migration --create table_name? Notice the difference between --create and --table

I'll see him again ...

- Yup let's go for it. Let's discuss how this should look and work in it's own issue

Great!.

- Ok, but then it would be good to create a convention, so that there are no problems with the names.

Excellent. I believe that craft would have to create by default adding "Controller" to the name, but if a user does not want it that way, it can be removed.

- Can you give a hard example of this? How would the flow of it work?

When I created my controller and wanted to show the results in a view, I expected there to be a template, I had to create it by hand.

- Command to create a default user.

For me, example:

craft create-user --username xxx --email xxx --pasword xxx

And I don't know if I forget some obligatory field.

**Comment by josephmancuso** [comment]
I created issues based on these. Closing down this issue.
