### ISSUE TITLE
moving core and craft to masonite repo

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#311]
I'm thinking what if we have everything in [one repo](https://github.com/MasoniteFramework/masonite). 

When we run `craft new`, Instead of cloning a repo, we can just have templates like the following installer.

Reference Intaller: https://github.com/phoenixframework/phoenix/tree/master/installer

Having a monolithic approach can solve [this](https://twitter.com/masoniteproject/status/1037879007998562305) and issue management problem too.

**Comment by josephmancuso** [comment]
I am thinking about moving craft somewhere for version 2. It is a lot of issues and headaches and since we are moving to pipenv officially in December (all Masonite developers will need pipenv) it may solve a few problems we have. People only have installation issues with Masonite. There are very few bugs. 

I would need a technical explanation of how this would work though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vaibhavmule** [comment]
I don't have a technical explanation at the moment, let me think through it. 

When will be pipenv will be added at least for development?

**Comment by josephmancuso** [comment]
It's added currently with the develop branch on the `masoniteframework/masonite` repo.

In order to create new projects with that branch you can do:

```
$ craft new project_name --branch develop
```

**Comment by josephmancuso** [comment]
oh is that what we are talking about here? I thought we were talking about getting rid of the craft command line tool and somehow making creating new applications etc consolidated 😅 .

**Comment by josephmancuso** [comment]
we can't consolidate the `/masonite` repo into `core` since that's what all of our sweet sweet stars are. And consolidating this repo into `/masonite` won't really be possible since we will lose all of the git history and branches that people have in development.

If we are really going for the issue approach here it's not too big of a deal since most issues are really open here and any that are open in Masonite i reopen here. 

The other approach is that we make an issue template which shows before a person creates an issue explaining to create issues in this repo

**Comment by vaibhavmule** [comment]
I was talking about consolidated project into one, as I can we might loose git history. 

We can close this issue or we can keep it on for issue.

But, We should have issue template.
