### ISSUE TITLE
Create a new Session Driver using Redis

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/core#407]
Create a new session driver to use Redis. Would enable sessions across load balancing.

**Comment by josephmancuso** [comment]
yeah I like it. I feel more confident now with integrating with services like RabbitMQ and Redis after working on #402 . Having a session driver for redis would be really cool and honestly I don't think it would be that difficult. Drivers are fairly simple to work with and you only need to implement like 7 different methods for session drivers

**Comment by mitchdennett** [comment]
Yeah, I was thinking about creating another queue integration using Redis but thought this would be simpler to just get used to Redis first. I actually think this should be super simple.

**Comment by josephmancuso** [comment]
agreed. A quick thing to note is that look at where the library imports are in #402 . They need to be lazily imported because they will be imported by default and exceptions will be thrown if the library does not exist. We don't want anyone having to install redis if they will never use it. It should be a:

1. Use it once, hit an exception with a very detailed message on how to fix it (`pip install x`)
2. pip install it
3. Life's good.

**Comment by hammacktony** [comment]
I was just thinking of implementing this myself.

**Comment by josephmancuso** [comment]
@mitchdennett still interested in this?

**Comment by mitchdennett** [comment]
@josephmancuso sorry man, Been busy with midterms. I've got most of it done.  Should be able to get it done this weekend

**Comment by josephmancuso** [comment]
take your time bud. Just wondering. Cleaning up some tickets for beta 3 release. Just checking. The next minor release is on Sunday if you want to get it done by then. If not we can do it in the next next minor

**Comment by josephmancuso** [comment]
gonna close this for now to get it out of the way, it can be reopened if someone wants to take a crack at it
