### ISSUE TITLE
Sass file does not compile when server run with -r flag

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#461]

**Comment by aisola** [comment]
Yeah, I actually did this on purpose. The reloading is already slow, so adding the sass build time to it made it unbearable (to me). With #472, the code reloading is much faster. I think eventually we'll be able to put a flag in there that optionally recompiles the sass. It would be even faster still if you had a separate watcher process. I think it would generally be a best practice to not have the Sass recompile on server restart because that could easily interrupt developer flow (especially so if there was a compile error in the Sass).
